import type { OutfitRecommendation } from "@/lib/outfit-recommendation";
import { OutfitCard } from "@/app/components/OutfitCard";
import { OutfitAdvice } from "@/app/components/OutfitAdvice";

const STYLE_DNA_DIMENSIONS: Record<
  number,
  Record<string, { label: string; desc: string }>
> = {
  0: {
    M: { label: "M", desc: "Minimal" },
    E: { label: "E", desc: "Expressive" },
  },
  1: {
    C: { label: "C", desc: "Classic" },
    D: { label: "D", desc: "Dynamic" },
  },
  2: {
    S: { label: "S", desc: "Sharp" },
    R: { label: "R", desc: "Relaxed" },
  },
  3: {
    N: { label: "N", desc: "Neutral" },
    B: { label: "B", desc: "Bold" },
  },
};

type Props = {
  data: OutfitRecommendation;
};

export function OutfitReport({ data }: Props) {
  const { styleDNA, styleDNASummary, styleTags, outfit, stylingAdvice } = data;
  const hasOutfit = outfit.pieces.length > 0 || outfit.title;

  return (
    <article className="outfit-report">
      <header className="outfit-report-header">
        <p className="outfit-report-eyebrow">AI Stylist Report</p>
        <h2 className="outfit-report-title">Your Curated Look</h2>
      </header>

      {/* Style Tags */}
      <section className="report-block report-block--style" aria-labelledby="style-tags-heading">
        <div className="report-block-head">
          <span className="report-block-icon" aria-hidden>
            ✦
          </span>
          <div>
            <h3 id="style-tags-heading" className="report-block-title">
              Style 标签
            </h3>
            <p className="report-block-sub">Style Tags · StyleDNA profile</p>
          </div>
        </div>

        {styleDNA && (
          <div className="wardrobe-style-dna wardrobe-style-dna--inline">
            <p className="wardrobe-style-dna-label">StyleDNA</p>
            <div
              className="wardrobe-style-dna-code"
              aria-label={`StyleDNA ${styleDNA}`}
            >
              {styleDNA.split("").map((letter, i) => (
                <span key={i} className="wardrobe-style-dna-letter">
                  {letter}
                </span>
              ))}
            </div>
            {styleDNASummary && (
              <p className="wardrobe-style-dna-summary">{styleDNASummary}</p>
            )}
            <div className="wardrobe-style-dna-legend">
              {styleDNA.split("").map((letter, i) => {
                const dim = STYLE_DNA_DIMENSIONS[i]?.[letter];
                return dim ? (
                  <span key={i}>
                    <strong>{dim.label}</strong> — {dim.desc}
                  </span>
                ) : null;
              })}
            </div>
          </div>
        )}

        {styleTags.length > 0 && (
          <div className="style-tag-cloud">
            {styleTags.map((tag) => (
              <span key={tag} className="style-tag-pill">
                {tag}
              </span>
            ))}
          </div>
        )}
      </section>

      {/* Outfit Card */}
      {hasOutfit && (
        <section
          className="report-block report-block--outfit"
          aria-labelledby="outfit-card-heading"
        >
          <div className="report-block-head">
            <span className="report-block-icon" aria-hidden>
              ◈
            </span>
            <div>
              <h3 id="outfit-card-heading" className="report-block-title">
                Outfit Card
              </h3>
              <p className="report-block-sub">Complete look breakdown</p>
            </div>
          </div>

          <p
            style={{
              marginBottom: "1rem",
              fontSize: "0.875rem",
              color: "#a1a1aa",
            }}
          >
            {outfit.title}
            {outfit.occasion ? ` · ${outfit.occasion}` : ""}
            {styleDNA ? (
              <span
                style={{
                  marginLeft: "0.5rem",
                  fontFamily: "var(--font-geist-mono), monospace",
                  color: "#c4b5fd",
                }}
              >
                {styleDNA}
              </span>
            ) : null}
          </p>
          <OutfitCard data={data} />
        </section>
      )}

      <OutfitAdvice advice={stylingAdvice} />

      <footer className="outfit-report-footer">
        <span>Generated by AI Wardrobe</span>
        {styleDNA && <span className="outfit-report-footer-code">{styleDNA}</span>}
      </footer>
    </article>
  );
}
